plt.hist(overtime_df["mlp_pred_-6"], alpha=1, bins = 5, label = "-6", range = [0, 1])
plt.hist(overtime_df["mlp_pred_-3"], alpha=.75, bins = 5, label = "-3", range = [0, 1])
plt.hist(overtime_df["mlp_pred_0"], alpha=.5, bins = 5, label = "0", range = [0, 1])
plt.hist(overtime_df["mlp_pred_3"], alpha=.5, bins = 5, label = "3", range = [0, 1])
plt.hist(overtime_df["mlp_pred_6"], alpha=.5, bins = 5, label = "6", range = [0, 1])
plt.legend()